rstudio:
  container_name: rstudio-mpm
  image: mattmalcher/gov_api_env:latest
  environment:
    - PASSWORD=mitt
  #default user is: rstudio
  volumes:
    - .:/home/rstudio/gov.uk.taxonomy
  ports:
    - 8787:8787
